#!/usr/bin/env bash

ICON_THEME="Papirus"
ICON_DIR="/usr/share/icons/$ICON_THEME"
if [ ! -d "$ICON_DIR" ]; then
    ICON_DIR="$HOME/.icons/$ICON_THEME"
fi

# Get Volume
get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}

# Get icons
get_icon() {
	current=$(get_volume)
	if [[ "$current" -eq "0" ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-volume-muted.svg"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-volume-low.svg"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-volume-medium.svg"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-volume-high.svg"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume) %"
}

# Increase Volume
inc_volume() {
	pactl set-sink-volume @DEFAULT_SINK@ +5% && notify_user
}

# Decrease Volume
dec_volume() {
	pactl set-sink-volume @DEFAULT_SINK@ -5% && notify_user
}

# Toggle Mute
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$ICON_DIR/48x48/status/notification-audio-volume-muted.svg" "Volume Switched OFF"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$(pamixer --default-source --get-mute)" == "false" ]; then
		pamixer --default-source -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$ICON_DIR/48x48/status/notification-audio-input-microphone-muted.svg" "Microphone Switched OFF"
	elif [ "$(pamixer --default-source --get-mute)" == "true" ]; then
		pamixer --default-source -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$ICON_DIR/48x48/status/notification-audio-input-microphone.svg" "Microphone Switched ON"
	fi
}

# Get icons for mic
get_mic_icon() {
	current=$(pamixer --default-source --get-volume)
	if [[ "$current" -eq "0" ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-input-microphone-muted.svg"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-input-microphone-low.svg"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-input-microphone-medium.svg"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "$ICON_DIR/48x48/status/notification-audio-input-microphone-high.svg"
	fi
}

# Notify mic
notify_mic_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(pamixer --default-source --get-volume) %"
}

# Increase MIC Volume
inc_mic_volume() {
	pamixer --default-source -i 5 && notify_mic_user
}

# Decrease MIC Volume
dec_mic_volume() {
	pamixer --default-source -d 5 && notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
	get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
