#!/bin/bash
kwalletd6 & disown

sleep 2
/usr/lib/pam_kwallet_init & disown

sleep 5
qdbus org.kde.kwalletd6 /modules/kwalletd6 open kdewallet 0 $0 & disown
qdbus org.kde.kwalletd6 /modules/kwalletd6 open "Default keyring" 0 $0 & disown
